package com.isep.desofs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CartAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartAllPropertiesEquals(Cart expected, Cart actual) {
        assertCartAutoGeneratedPropertiesEquals(expected, actual);
        assertCartAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartAllUpdatablePropertiesEquals(Cart expected, Cart actual) {
        assertCartUpdatableFieldsEquals(expected, actual);
        assertCartUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartAutoGeneratedPropertiesEquals(Cart expected, Cart actual) {
        assertThat(expected)
            .as("Verify Cart auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartUpdatableFieldsEquals(Cart expected, Cart actual) {
        assertThat(expected)
            .as("Verify Cart relevant properties")
            .satisfies(e -> assertThat(e.getTotal()).as("check total").isEqualTo(actual.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCartUpdatableRelationshipsEquals(Cart expected, Cart actual) {
        assertThat(expected)
            .as("Verify Cart relationships")
            .satisfies(e -> assertThat(e.getPayment()).as("check payment").isEqualTo(actual.getPayment()));
    }
}
