@startuml UseCaseDiagram

left to right direction

actor Guest

actor Attacker

usecase (Sign Up)
usecase (Login)

usecase (Brute Force Attack)#Red
usecase (Automated Registration) #Red
usecase (Credential Theft) #Red
usecase (Session Hijacking) #Red
usecase (Account Takeover) #Red


(Automated Registration)<-- Attacker:exploits
(Brute Force Attack)<-- Attacker:exploits
(Credential Theft)<-- Attacker:exploits
(Session Hijacking)<-- Attacker:exploits
(Account Takeover)<-- Attacker:exploits

(Sign Up) <-- (Automated Registration)
(Login) <-- (Brute Force Attack)
(Login) <-- (Credential Theft)
(Login) <-- (Session Hijacking)
(Login) <-- (Account Takeover)

Guest --> (Sign Up)
Guest --> (Login)



@enduml