@startuml

left to right direction

actor Photographer
actor Attacker

usecase (Add Photo To Cart)
usecase (Denial of Service) #Red
usecase (Unauthorized Access) #Red
usecase (Data Manipulation) #Red

Photographer -------> (Add Photo To Cart)
Attacker -up-> (Denial of Service)
Attacker -up-> (Unauthorized Access)
Attacker -up-> (Data Manipulation)



(Denial of Service) -up-> (Add Photo To Cart) : threatens
(Unauthorized Access) -up-> (Add Photo To Cart) : threatens
(Data Manipulation) -up-> (Add Photo To Cart) : threatens

@enduml