# This workflow must build and run backend tests
name: "Build backend and run it tests"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    status-backend:
        runs-on: ubuntu-latest
        steps:
            # 1. get the code from repo
            - name: "Check out Git repository"
              uses: actions/checkout@v4.0.0
            # 2. install java
            - name: "Use Java 21"
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'adopt'
            # 3. build
            - name: "Doing Clean Compile"
              working-directory: AngularProject
              run: mvn clean compile
            # 4. run tests
            - name: "Running tests"
              working-directory: AngularProject
              run: mvn test
