# This workflow must build and run backend tests
name: "Nightly Build"

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AngularProject

    strategy:
      matrix:
        node-version: [20.12.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: AngularProject/package-lock.json

      - name: Display Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Clean up front-end
        run: rm -rf dist

  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AngularProject

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Set up Maven 3.9.5
        uses: s4u/maven-action@v2
        with:
          maven-version: '3.9.5'

      - name: Clean and compile
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=DESOFS -Dsonar.projectName='DESOFS'

      - name: Clean up back-end
        run: mvn clean