name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AngularProject

    strategy:
      matrix:
        node-version: [20.12.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: AngularProject/package-lock.json

      - name: Display Node.js version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run prettier check
        run: npm run prettier:check

      - name: Set up Java 
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Clean and compile
        run: mvn clean compile