name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AngularProject

    strategy:
      matrix:
        node-version: [20.12.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List directory contents for debugging
        run: ls -R

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: List AngularProject directory for debugging
        run: ls -R AngularProject

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run prettier check
        run: npm run prettier:check

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            *.log
